# Deny all warnings by default
warns = [
  "clippy::all",
  "clippy::pedantic",
]

# Allow a small set of pedantic lints we find too noisy
allow = [
  "clippy::module_name_repetitions",
  "clippy::missing_panics_doc",
]
